algoritmo "Cálculo de média aritmética"
// Função :
// Autor :
// Data : 21/08/12
// Seção de Declarações 
var A, B, Media: real

inicio

escreval("Programa que calcula a média aritmética de dois valores.")
escreval
escreval("Digite um valor: ")
leia(A)
escreval("Digite outro valor: ")
leia(B)

Media<-(A+B)/2

escreval("A média dos dois valores é: ",media)

// Seção de Comandos 
fimalgoritmo
