algoritmo "Exemplo 3"
// Função :
// Autor :
// Data : 21/08/12
// Seção de Declarações 
var A, B, X: real

inicio
// Seção de Comandos

escreval("Entre com um valor para A: ")
leia (A)

escreval("Entre com um valor para B: ")
leia (B)

X<-(A+B)/(A-B)

escreval("O valor de A lido foi ", A," e o valor de B lido foi: ", B)

escreval("Para os valores de A e B lidos, o resultado da expressão X=(A+B)/(A-B), será: ", X)

fimalgoritmo
