algoritmo "Menu"
// Função :
// Autor :
// Data : 04/09/2012
// Seção de Declarações 
var
opcao: inteiro

inicio
// Seção de Comandos
repita
   limpatela
   escreval("- Cadastro de clientes:")
   escreval("1 - Incluir")
   escreval("2 - Alterar")
   escreval("3 - Consultar")
   escreval("4 - Excluir")
   escreval("5 - Sair")
   escreval
   leia(opcao)
   escreval
   escreval("Você escolheu a opção: ", opcao," - Sair.")
ate opcao = 5

fimalgoritmo
