algoritmo "Negativo ou positivo?"
// Função :
// Autor :
// Data : 29/08/2012
// Seção de Declarações 
var

num: real

inicio
// Seção de Comandos

escreva("Digite um número: ")
leia(num)

se num < 0 entao
   escreval("O número digitado é negativo!")
senao
   escreval("O número digitado é positivo!")
fimse

escreva("O número digitado foi: ", num, ".")

escreval

fimalgoritmo
